queue_rules:
  - name: default
    merge_method: squash
    update_method: merge
    queue_conditions:
      - base=main
      - '-draft'
    merge_conditions:
      - check-success=All green
      - check-success=Run zizmor

pull_request_rules:
  - name: Queue pull requests
    conditions:
      - base=main
      - '-draft'
    actions:
      queue:
        name: default
