#!/bin/sh -e

# Run the Python test suite under coverage.

if [ -z "$GITHUB_ACTIONS" ]; then
    scripts/check
fi

set -x

.venv/bin/coverage run -m pytest "$@"
.venv/bin/coverage combine
.venv/bin/coverage report
